# Generated by Django 4.2 on 2023-04-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_marker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
