# Generated by Django 4.2 on 2023-04-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_delete_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
