# Generated by Django 4.2 on 2023-04-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_nodes_latitude_alter_nodes_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='Latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='Longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
